apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      application: http-server
  template:
    metadata:
      labels:
        application: http-server
    spec:
      containers:
      - name: server
        env:
        - name: RATE_LIMIT
          value: "1"
        image: quay.io/ted_ross/throttle-service-jvm
        imagePullPolicy: IfNotPresent
